import React from "react";
import Head from "next/head";

import TesteImage from "../../../assets/images/teste.svg";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <h1>sou uma nvoa homne</h1>
        <img src={TesteImage} alt="mudou" />
      </main>
      <footer></footer>
    </div>
  );
}
